### ISSUE TITLE
enyo 2.7 for LuneOS/webOS

### ISSUE THREAD

**Issue by bbito** [codepoet80/webos-simplechat#2]
Hi codepoet, I lurk on the webos-ports irc logs and see that you're working with enyo2. I did a little work with enyo 2.7 back in the day and wanted to let you know about a repo I have that you may find useful but didn't know a better way to reach out than this GH issue...
https://github.com/bbito/onyx-webos-app

**Comment by codepoet80** [comment]
Awesome, thank you! More detailed reply in your [Discussion thread](https://github.com/bbito/onyx-webos-app/discussions/2).
